// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: proto/index.proto

package indexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SymbolScope int32

const (
	SymbolScope_SYMBOL_SCOPE_UNSPECIFIED SymbolScope = 0
	SymbolScope_LOCAL                    SymbolScope = 1
	SymbolScope_GLOBAL                   SymbolScope = 2
)

// Enum value maps for SymbolScope.
var (
	SymbolScope_name = map[int32]string{
		0: "SYMBOL_SCOPE_UNSPECIFIED",
		1: "LOCAL",
		2: "GLOBAL",
	}
	SymbolScope_value = map[string]int32{
		"SYMBOL_SCOPE_UNSPECIFIED": 0,
		"LOCAL":                    1,
		"GLOBAL":                   2,
	}
)

func (x SymbolScope) Enum() *SymbolScope {
	p := new(SymbolScope)
	*p = x
	return p
}

func (x SymbolScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SymbolScope) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_index_proto_enumTypes[0].Descriptor()
}

func (SymbolScope) Type() protoreflect.EnumType {
	return &file_proto_index_proto_enumTypes[0]
}

func (x SymbolScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SymbolScope.Descriptor instead.
func (SymbolScope) EnumDescriptor() ([]byte, []int) {
	return file_proto_index_proto_rawDescGZIP(), []int{0}
}

type SymbolType int32

const (
	SymbolType_SYMBOL_TYPE_UNSPECIFIED SymbolType = 0
	SymbolType_FUNCTION                SymbolType = 1
	SymbolType_FILE                    SymbolType = 2
	SymbolType_MODULE                  SymbolType = 3
	SymbolType_DIRECTORY               SymbolType = 4
)

// Enum value maps for SymbolType.
var (
	SymbolType_name = map[int32]string{
		0: "SYMBOL_TYPE_UNSPECIFIED",
		1: "FUNCTION",
		2: "FILE",
		3: "MODULE",
		4: "DIRECTORY",
	}
	SymbolType_value = map[string]int32{
		"SYMBOL_TYPE_UNSPECIFIED": 0,
		"FUNCTION":                1,
		"FILE":                    2,
		"MODULE":                  3,
		"DIRECTORY":               4,
	}
)

func (x SymbolType) Enum() *SymbolType {
	p := new(SymbolType)
	*p = x
	return p
}

func (x SymbolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SymbolType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_index_proto_enumTypes[1].Descriptor()
}

func (SymbolType) Type() protoreflect.EnumType {
	return &file_proto_index_proto_enumTypes[1]
}

func (x SymbolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SymbolType.Descriptor instead.
func (SymbolType) EnumDescriptor() ([]byte, []int) {
	return file_proto_index_proto_rawDescGZIP(), []int{1}
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	RootPath      string                 `protobuf:"bytes,2,opt,name=root_path,json=rootPath,proto3" json:"root_path,omitempty"`
	Modules       []*Module              `protobuf:"bytes,3,rep,name=modules,proto3" json:"modules,omitempty"`
	Objects       []*Object              `protobuf:"bytes,4,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_proto_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_proto_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_proto_index_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *Project) GetRootPath() string {
	if x != nil {
		return x.RootPath
	}
	return ""
}

func (x *Project) GetModules() []*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *Project) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type Module struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalId       int64                  `protobuf:"varint,1,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"` // Unique within project
	ModuleName    string                 `protobuf:"bytes,2,opt,name=module_name,json=moduleName,proto3" json:"module_name,omitempty"`
	Symbols       []*Symbol              `protobuf:"bytes,3,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_proto_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_proto_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_proto_index_proto_rawDescGZIP(), []int{1}
}

func (x *Module) GetLocalId() int64 {
	if x != nil {
		return x.LocalId
	}
	return 0
}

func (x *Module) GetModuleName() string {
	if x != nil {
		return x.ModuleName
	}
	return ""
}

func (x *Module) GetSymbols() []*Symbol {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type Object struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LocalId         int64                  `protobuf:"varint,1,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`          // Unique within project
	ModuleId        *int64                 `protobuf:"varint,2,opt,name=module_id,json=moduleId,proto3,oneof" json:"module_id,omitempty"` // References Module.local_id when set
	ModulePath      string                 `protobuf:"bytes,3,opt,name=module_path,json=modulePath,proto3" json:"module_path,omitempty"`
	FilesystemPath  string                 `protobuf:"bytes,4,opt,name=filesystem_path,json=filesystemPath,proto3" json:"filesystem_path,omitempty"` // Metadata only, never used for filesystem access
	Filetype        string                 `protobuf:"bytes,5,opt,name=filetype,proto3" json:"filetype,omitempty"`
	Content         []byte                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                                        // Object content (content_hash computed server-side)
	SymbolInstances []*SymbolInstance      `protobuf:"bytes,7,rep,name=symbol_instances,json=symbolInstances,proto3" json:"symbol_instances,omitempty"` // Symbol instances in this object
	Refs            []*SymbolRef           `protobuf:"bytes,8,rep,name=refs,proto3" json:"refs,omitempty"`                                              // References from this object
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Object) Reset() {
	*x = Object{}
	mi := &file_proto_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Object) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Object) ProtoMessage() {}

func (x *Object) ProtoReflect() protoreflect.Message {
	mi := &file_proto_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Object.ProtoReflect.Descriptor instead.
func (*Object) Descriptor() ([]byte, []int) {
	return file_proto_index_proto_rawDescGZIP(), []int{2}
}

func (x *Object) GetLocalId() int64 {
	if x != nil {
		return x.LocalId
	}
	return 0
}

func (x *Object) GetModuleId() int64 {
	if x != nil && x.ModuleId != nil {
		return *x.ModuleId
	}
	return 0
}

func (x *Object) GetModulePath() string {
	if x != nil {
		return x.ModulePath
	}
	return ""
}

func (x *Object) GetFilesystemPath() string {
	if x != nil {
		return x.FilesystemPath
	}
	return ""
}

func (x *Object) GetFiletype() string {
	if x != nil {
		return x.Filetype
	}
	return ""
}

func (x *Object) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Object) GetSymbolInstances() []*SymbolInstance {
	if x != nil {
		return x.SymbolInstances
	}
	return nil
}

func (x *Object) GetRefs() []*SymbolRef {
	if x != nil {
		return x.Refs
	}
	return nil
}

type Symbol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalId       int64                  `protobuf:"varint,1,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"` // Unique within project
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Scope         SymbolScope            `protobuf:"varint,3,opt,name=scope,proto3,enum=askl.index.SymbolScope" json:"scope,omitempty"`
	Type          SymbolType             `protobuf:"varint,4,opt,name=type,proto3,enum=askl.index.SymbolType" json:"type,omitempty"` // Function, File, Module, or Directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Symbol) Reset() {
	*x = Symbol{}
	mi := &file_proto_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Symbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Symbol) ProtoMessage() {}

func (x *Symbol) ProtoReflect() protoreflect.Message {
	mi := &file_proto_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Symbol.ProtoReflect.Descriptor instead.
func (*Symbol) Descriptor() ([]byte, []int) {
	return file_proto_index_proto_rawDescGZIP(), []int{3}
}

func (x *Symbol) GetLocalId() int64 {
	if x != nil {
		return x.LocalId
	}
	return 0
}

func (x *Symbol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Symbol) GetScope() SymbolScope {
	if x != nil {
		return x.Scope
	}
	return SymbolScope_SYMBOL_SCOPE_UNSPECIFIED
}

func (x *Symbol) GetType() SymbolType {
	if x != nil {
		return x.Type
	}
	return SymbolType_SYMBOL_TYPE_UNSPECIFIED
}

type SymbolInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SymbolLocalId int64                  `protobuf:"varint,1,opt,name=symbol_local_id,json=symbolLocalId,proto3" json:"symbol_local_id,omitempty"` // References Symbol.local_id
	StartOffset   int32                  `protobuf:"varint,3,opt,name=start_offset,json=startOffset,proto3" json:"start_offset,omitempty"`
	EndOffset     int32                  `protobuf:"varint,4,opt,name=end_offset,json=endOffset,proto3" json:"end_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolInstance) Reset() {
	*x = SymbolInstance{}
	mi := &file_proto_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolInstance) ProtoMessage() {}

func (x *SymbolInstance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolInstance.ProtoReflect.Descriptor instead.
func (*SymbolInstance) Descriptor() ([]byte, []int) {
	return file_proto_index_proto_rawDescGZIP(), []int{4}
}

func (x *SymbolInstance) GetSymbolLocalId() int64 {
	if x != nil {
		return x.SymbolLocalId
	}
	return 0
}

func (x *SymbolInstance) GetStartOffset() int32 {
	if x != nil {
		return x.StartOffset
	}
	return 0
}

func (x *SymbolInstance) GetEndOffset() int32 {
	if x != nil {
		return x.EndOffset
	}
	return 0
}

type SymbolRef struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ToSymbolLocalId int64                  `protobuf:"varint,1,opt,name=to_symbol_local_id,json=toSymbolLocalId,proto3" json:"to_symbol_local_id,omitempty"` // References Symbol.local_id (unique within project)
	FromOffsetStart int32                  `protobuf:"varint,2,opt,name=from_offset_start,json=fromOffsetStart,proto3" json:"from_offset_start,omitempty"`
	FromOffsetEnd   int32                  `protobuf:"varint,3,opt,name=from_offset_end,json=fromOffsetEnd,proto3" json:"from_offset_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SymbolRef) Reset() {
	*x = SymbolRef{}
	mi := &file_proto_index_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolRef) ProtoMessage() {}

func (x *SymbolRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_index_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolRef.ProtoReflect.Descriptor instead.
func (*SymbolRef) Descriptor() ([]byte, []int) {
	return file_proto_index_proto_rawDescGZIP(), []int{5}
}

func (x *SymbolRef) GetToSymbolLocalId() int64 {
	if x != nil {
		return x.ToSymbolLocalId
	}
	return 0
}

func (x *SymbolRef) GetFromOffsetStart() int32 {
	if x != nil {
		return x.FromOffsetStart
	}
	return 0
}

func (x *SymbolRef) GetFromOffsetEnd() int32 {
	if x != nil {
		return x.FromOffsetEnd
	}
	return 0
}

var File_proto_index_proto protoreflect.FileDescriptor

const file_proto_index_proto_rawDesc = "" +
	"\n" +
	"\x11proto/index.proto\x12\n" +
	"askl.index\"\xa5\x01\n" +
	"\aProject\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12\x1b\n" +
	"\troot_path\x18\x02 \x01(\tR\brootPath\x12,\n" +
	"\amodules\x18\x03 \x03(\v2\x12.askl.index.ModuleR\amodules\x12,\n" +
	"\aobjects\x18\x04 \x03(\v2\x12.askl.index.ObjectR\aobjects\"r\n" +
	"\x06Module\x12\x19\n" +
	"\blocal_id\x18\x01 \x01(\x03R\alocalId\x12\x1f\n" +
	"\vmodule_name\x18\x02 \x01(\tR\n" +
	"moduleName\x12,\n" +
	"\asymbols\x18\x03 \x03(\v2\x12.askl.index.SymbolR\asymbols\"\xc5\x02\n" +
	"\x06Object\x12\x19\n" +
	"\blocal_id\x18\x01 \x01(\x03R\alocalId\x12 \n" +
	"\tmodule_id\x18\x02 \x01(\x03H\x00R\bmoduleId\x88\x01\x01\x12\x1f\n" +
	"\vmodule_path\x18\x03 \x01(\tR\n" +
	"modulePath\x12'\n" +
	"\x0ffilesystem_path\x18\x04 \x01(\tR\x0efilesystemPath\x12\x1a\n" +
	"\bfiletype\x18\x05 \x01(\tR\bfiletype\x12\x18\n" +
	"\acontent\x18\x06 \x01(\fR\acontent\x12E\n" +
	"\x10symbol_instances\x18\a \x03(\v2\x1a.askl.index.SymbolInstanceR\x0fsymbolInstances\x12)\n" +
	"\x04refs\x18\b \x03(\v2\x15.askl.index.SymbolRefR\x04refsB\f\n" +
	"\n" +
	"_module_id\"\x92\x01\n" +
	"\x06Symbol\x12\x19\n" +
	"\blocal_id\x18\x01 \x01(\x03R\alocalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12-\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x17.askl.index.SymbolScopeR\x05scope\x12*\n" +
	"\x04type\x18\x04 \x01(\x0e2\x16.askl.index.SymbolTypeR\x04type\"\x80\x01\n" +
	"\x0eSymbolInstance\x12&\n" +
	"\x0fsymbol_local_id\x18\x01 \x01(\x03R\rsymbolLocalId\x12!\n" +
	"\fstart_offset\x18\x03 \x01(\x05R\vstartOffset\x12\x1d\n" +
	"\n" +
	"end_offset\x18\x04 \x01(\x05R\tendOffsetJ\x04\b\x02\x10\x03\"\x8c\x01\n" +
	"\tSymbolRef\x12+\n" +
	"\x12to_symbol_local_id\x18\x01 \x01(\x03R\x0ftoSymbolLocalId\x12*\n" +
	"\x11from_offset_start\x18\x02 \x01(\x05R\x0ffromOffsetStart\x12&\n" +
	"\x0ffrom_offset_end\x18\x03 \x01(\x05R\rfromOffsetEnd*B\n" +
	"\vSymbolScope\x12\x1c\n" +
	"\x18SYMBOL_SCOPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05LOCAL\x10\x01\x12\n" +
	"\n" +
	"\x06GLOBAL\x10\x02*\\\n" +
	"\n" +
	"SymbolType\x12\x1b\n" +
	"\x17SYMBOL_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bFUNCTION\x10\x01\x12\b\n" +
	"\x04FILE\x10\x02\x12\n" +
	"\n" +
	"\x06MODULE\x10\x03\x12\r\n" +
	"\tDIRECTORY\x10\x04B<Z:github.com/planetA/askl-golang-indexer/pkg/indexpb;indexpbb\x06proto3"

var (
	file_proto_index_proto_rawDescOnce sync.Once
	file_proto_index_proto_rawDescData []byte
)

func file_proto_index_proto_rawDescGZIP() []byte {
	file_proto_index_proto_rawDescOnce.Do(func() {
		file_proto_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_index_proto_rawDesc), len(file_proto_index_proto_rawDesc)))
	})
	return file_proto_index_proto_rawDescData
}

var file_proto_index_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_index_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_index_proto_goTypes = []any{
	(SymbolScope)(0),       // 0: askl.index.SymbolScope
	(SymbolType)(0),        // 1: askl.index.SymbolType
	(*Project)(nil),        // 2: askl.index.Project
	(*Module)(nil),         // 3: askl.index.Module
	(*Object)(nil),         // 4: askl.index.Object
	(*Symbol)(nil),         // 5: askl.index.Symbol
	(*SymbolInstance)(nil), // 6: askl.index.SymbolInstance
	(*SymbolRef)(nil),      // 7: askl.index.SymbolRef
}
var file_proto_index_proto_depIdxs = []int32{
	3, // 0: askl.index.Project.modules:type_name -> askl.index.Module
	4, // 1: askl.index.Project.objects:type_name -> askl.index.Object
	5, // 2: askl.index.Module.symbols:type_name -> askl.index.Symbol
	6, // 3: askl.index.Object.symbol_instances:type_name -> askl.index.SymbolInstance
	7, // 4: askl.index.Object.refs:type_name -> askl.index.SymbolRef
	0, // 5: askl.index.Symbol.scope:type_name -> askl.index.SymbolScope
	1, // 6: askl.index.Symbol.type:type_name -> askl.index.SymbolType
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_index_proto_init() }
func file_proto_index_proto_init() {
	if File_proto_index_proto != nil {
		return
	}
	file_proto_index_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_index_proto_rawDesc), len(file_proto_index_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_index_proto_goTypes,
		DependencyIndexes: file_proto_index_proto_depIdxs,
		EnumInfos:         file_proto_index_proto_enumTypes,
		MessageInfos:      file_proto_index_proto_msgTypes,
	}.Build()
	File_proto_index_proto = out.File
	file_proto_index_proto_goTypes = nil
	file_proto_index_proto_depIdxs = nil
}
